import "./styles.css";
import "../lib/orpc.server";

import { cn } from "@bluevoid-test/ui/utils";
import type { Metadata } from "next";
import { Geist } from "next/font/google";
import { ReactQueryProvider } from "@/lib/query-client";
import Header from "./_components/Header";

export const metadata: Metadata = {
	title: "Create T3 App",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
	subsets: ["latin"],
	variable: "--font-geist-sans",
});

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html className={`${geist.variable}`} lang="en">
			<body>
				<Header />
				<main
					className={cn(
						"min-h-screen pt-14 transition-all",
						// !isMobile && "pl-[5.5rem]",
					)}
				>
					<ReactQueryProvider>{children}</ReactQueryProvider>
				</main>
			</body>
		</html>
	);
}
